### ISSUE TITLE
Invalid File Signature Error

### ISSUE THREAD

**Issue by joeHillman** [applitools/eyes.images.javascript#6]
## Invalid File Signature Error when submitting an image to the eyes service.
* When looking at the tests that are in queue, the test remains in progress.
* While in progress, there does not appear to be a timeout to abort the test consistently. I've witnessed this once where it aborts the test in progress.
* A co worker has been able to successfully submit but in an inconsistent fashion.
* When there is an error on his end, it is the same error and log output that I have.
* Best we can tell is that there's a problem on the service end.
* This issue may be related to the eyes utils module.

### Log Output
```
12/04/2017 12:53:22 pm - info: Eyes: EyesBase.checkWindow - session started - creating match window task
12/04/2017 12:53:22 pm - info: Eyes: notifying event:  validationWillStart
12/04/2017 12:53:22 pm - info: Eyes: EyesBase.checkWindow - calling matchWindowTask.matchWindow
12/04/2017 12:53:22 pm - info: Eyes: MatchWindowTask.matchWindow called with shouldRunOnceOnRetryTimeout:  false , ignoreMismatch: false , retryTimeout: -1
12/04/2017 12:53:22 pm - info: Eyes: MatchWindowTask.matchWindow starting to perform the match process
12/04/2017 12:53:22 pm - info: Eyes: MatchWindowTask.matchWindow - starting retry sequence. start: 1492001602873
12/04/2017 12:53:22 pm - info: Eyes: MatchWindowTask._retryMatch will retry
12/04/2017 12:53:22 pm - info: Eyes: MatchWindowTask._retryMatch calls for app output
12/04/2017 12:53:22 pm - info: Eyes: EyesBase.checkWindow - getAppOutput callback is running - getting screenshot
12/04/2017 12:53:22 pm - info: Eyes: EyesBase.checkWindow - getAppOutput received the screenshot
```

### Error Message
```
jhillman-mb:frontend-admin joe$ ./node_modules/.bin/nightwatch ./test/nightwatch-tests/nightWatchSecond.js --env=visual
Starting selenium server... started - PID:  6014

[Night Watch Second] Test Suite
===================================

Running:  Test
(node:6013) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
 ✔ Testing if the page title equals "Google".
 ✖ Error: Invalid file signature
    at ReadableBufferStream.ondata (_stream_readable.js:555:20)
    at ReadableBufferStream.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)

FAILED:  1 errors and 1 passed (13.14s)

 _________________________________________________

 TEST FAILURE: 1 error during execution,  0 assertions failed, 1 passed. (13.725s)

 ✖ nightWatchSecond

   - Test (13.14s)

     Error while running [Night Watch Second / Test]:

     Error: Invalid file signature
       at ReadableBufferStream.ondata (_stream_readable.js:555:20)
       at ReadableBufferStream.Readable.read (_stream_readable.js:381:10)
       at flow (_stream_readable.js:761:34)
```

**Comment by danielputerman** [comment]
Hi, thanks for the feedback, apologies for the late reply. A few points:

1. At the moment, tests in Applitools do not time out on their own. They end when there's either a call to **close** or **abortIfNotClosed**. See example here:
https://applitools.com/resources/tutorial/screenshots/javascript

2. Regarding the invalid signature, we haven't encountered any such thing before. Can you create a example test which reproduces the problem? 

Thanks!

**Comment by danielputerman** [comment]
@joeHillman Following up? Does this still happen? Can you send me an example test which reproduces the issue?

**Comment by joeHillman** [comment]
Haven't had the cycles for this work lately, though I think I'll be picking it back up over the next week or two. Will let you know what I find. Thanks @danielputerman.

**Comment by mekdev** [comment]
I am also hitting the same issue 

```
2017-08-14T15:55:53.044Z - info: (common.js:54) High zoom
2017-08-14T15:55:53.045Z - info: (common.js:54) <Buffer 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d 22 55 54 46 2d 38 22 3f 3e 0a 3c 45 72 72 6f 72 3e 3c 43 6f 64 ... >

Error: Invalid file signature
    at ReadableBufferStream.ondata (_stream_readable.js:555:20)
    at ReadableBufferStream.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

The concern is that this test used to passed before. This is just a png image.

You can see our old test run at https://eyes.applitools.com/app/batches/00000251901382280448?display=thumbnails&accountId=m989aQAuq8e107L5sKPP9tWCCPU10JcYV8FtXpBk1pRrlE110&top=00000251899574941266(90)

**Comment by mekdev** [comment]
Ok looks like I found the reason. I downloaded the file and it seems like the png is corrupted. 
![staging-wmtsorthohighzoom](https://user-images.githubusercontent.com/2752830/29282208-d69bdf04-80d6-11e7-9680-e28e4eef2708.png)

Still it would be nice to have proper stack traces to the line that threw the error in the test (Mocha)

**Comment by danielputerman** [comment]
Hi @mekdev, cool. I was suspecting this was the reason, thanks for updating.
I'll see what we can do about the stack trace of course.
